const express = require('express');
const auth = require('./controllers/auth');
const path = require('path');
const userRoutes = require('./routes/user');

const app = express();

// Middleware for sending JSON
app.use(express.json());

// Serving static files
app.use(express.static(path.join(__dirname + '/public')));


app.use('/api/v1/users', userRoutes);

app.get('/api', (req, res) => {
	res.status(200).json({
		status: 200,
		message: {
			data: [
				100,
				200,
				300
			]
		}
	});
});



// public folder was generated by vue-cli after we run build
// loading our vue
app.get('*', (req, res) => {
	// Use this if not SPA
	// res.status(200).render('index.html');
	res.sendFile(path.join(__dirname, 'public','index.html'));
});

module.exports = app;
