const express = require('express');
const auth = require('./controllers/auth.js');

const app = express();

// Middleware for sending JSON
app.use(express.json());

// Serving static files
app.use(express.static(__dirname + '/public'));

// public folder was generated by vue-cli after we run build
// loading our vue
app.get('/', (req, res) => {
	res.status(200).render('index.html');
});


module.exports = app;
